### ISSUE TITLE
Create a new release and PyPI package

### ISSUE THREAD

**Issue by JFM9** [PaulSec/crt.sh#10]
The project could benefit of a new release tag and PyPI package.

The `crtsh.crtshAPI.search` function can currently take the `expired` argument which is not in the latest `0.2.0` version.

Adding a new version and package release would allow packages which depend on this project to download it directly from PyPI and use these new features by including it directly in a package's `setup.py` and `requirements.txt`.

**Comment by PaulSec** [comment]
Hi there, 

This has been fixed, feel free to check it out :)
