### ISSUE TITLE
Domain JSON object off?

### ISSUE THREAD

**Issue by killswitch-GUI** [PaulSec/crt.sh#5]
[...{"crtsh_id": "114422", "pem_url": "https://crt.sh/?d=114422", "logged_at": "2013-03-26", "not_before": "2011-07-08", "domain": "2014-07-07", "issuer": "*.uber.com"}...]

Seems its not just returning a date in the domain field, is this API side?

**Comment by PaulSec** [comment]
Hi there, 

I am just returning the value I got from crt.sh for the moment but I could modify it to actually have proper Date object. 
Otherwise, feel free to send me a PR and I will happily merge it. 

Cheers,

**Comment by PaulSec** [comment]
Hey there, did you manage to do what you wanted? 
I will close the issue so far but if you really get in trouble, let me know and we can work on something out. 

Cheers,
